# Generated by Django 5.1.5 on 2025-02-11 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('review_text', models.TextField(default='[хорошый книга')),
                ('stars', models.CharField(choices=[('☀☀', '☀☀'), ('☀☀☀', '☀☀☀'), ('☀☀☀☀', '☀☀☀☀'), ('☀☀☀☀☀', '☀☀☀☀☀'), ('☀☀☀☀☀☀', '☀☀☀☀☀☀')], default='☀☀☀', max_length=10)),
                ('choices_books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.books')),
            ],
        ),
    ]
