# Generated by Django 5.1.5 on 2025-02-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(blank=True, default='Аноним', max_length=100, null=True, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.CharField(choices=[('☀☀', '☀☀'), ('☀☀☀', '☀☀☀'), ('☀☀☀☀', '☀☀☀☀'), ('☀☀☀☀☀', '☀☀☀☀☀')], default='☀☀☀', max_length=10),
        ),
    ]
