# Generated by Django 5.1.5 on 2025-02-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_books_music'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'Книгу', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(max_length=30, verbose_name='Укажите автора '),
        ),
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.TextField(blank=True, verbose_name='Укажите описание книги '),
        ),
        migrations.AlterField(
            model_name='books',
            name='director',
            field=models.CharField(default='Дейл Карнеги', max_length=100),
        ),
        migrations.AlterField(
            model_name='books',
            name='genre',
            field=models.CharField(choices=[('DRAMA', 'DRAMA'), ('ROMAN', 'ROMAN'), ('FANTASY', 'FANTASY')], default='DRAMA', max_length=10, verbose_name='Выберите жанр'),
        ),
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(upload_to='book_images/', verbose_name='Загрузите фото'),
        ),
        migrations.AlterField(
            model_name='books',
            name='mail',
            field=models.CharField(max_length=30, verbose_name='Укажите почту автора '),
        ),
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.PositiveIntegerField(default=200, verbose_name='Укажите цену '),
        ),
        migrations.AlterField(
            model_name='books',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Укажите время '),
        ),
        migrations.AlterField(
            model_name='books',
            name='times',
            field=models.TimeField(blank=True, null=True, verbose_name='Укажите время просмотра '),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Укажите название книги '),
        ),
        migrations.AlterField(
            model_name='books',
            name='trailer',
            field=models.URLField(verbose_name='Укажите ссылку из YouTube'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.TextField(default='Хорошая книга'),
        ),
    ]
