# Generated by Django 5.1.5 on 2025-02-14 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0003_review_name_alter_review_stars'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('choice_status', models.CharField(choices=[('Чмтал', 'Читал'), ('Не читал', 'Не читал')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('choice_books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books')),
            ],
        ),
    ]
